git:
  mainBranches:
    - master
    - main
    - trunk
  ignoreWhitespaceInDiffView: true
  pagers:
    - pager: delta --dark --paging=never

quitOnTopLevelReturn: true
os:
  edit: "zed {{filename}}"
  editAtLine: "zed {{filename}}:{{line}}"
